services:
  - type: web
    name: fastapi-backend
    env: python
    pythonVersion: 3.11
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
      pip install torch==2.5.1+cpu --extra-index-url https://download.pytorch.org/whl/cpu
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    workingDir: backend
    envVars:
      - key: HUGGINGFACE_TOKEN
        sync: false
      - key: FIREBASE_JSON_STRING
        sync: false
